# Generated by Django 4.0.2 on 2022-08-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='import1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=122)),
                ('vesselid', models.CharField(max_length=60)),
                ('callsign', models.CharField(max_length=122)),
                ('cflag', models.CharField(max_length=122)),
                ('datoa', models.DateField()),
                ('service', models.CharField(max_length=122)),
                ('arrival', models.DateField()),
                ('captain', models.CharField(max_length=122)),
                ('noc', models.IntegerField()),
                ('lc', models.CharField(max_length=122)),
                ('cio', models.CharField(max_length=122)),
                ('hdo', models.CharField(max_length=122)),
                ('pic', models.CharField(max_length=122)),
                ('smembers', models.TextField()),
                ('cclear', models.CharField(max_length=122)),
                ('bno', models.CharField(max_length=122)),
                ('tid', models.CharField(max_length=122)),
                ('amount', models.IntegerField()),
                ('fuel', models.CharField(max_length=122)),
                ('fq', models.IntegerField()),
                ('fquality', models.CharField(max_length=122)),
                ('hsp', models.CharField(max_length=122)),
            ],
        ),
    ]
