# Generated by Django 4.1 on 2022-08-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_export1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passportnumber', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('designation', models.CharField(max_length=122)),
                ('country', models.CharField(max_length=122)),
                ('dateoa', models.DateField()),
                ('workpermit', models.CharField(max_length=20)),
                ('vesselid', models.CharField(max_length=122)),
            ],
        ),
        migrations.AlterField(
            model_name='import1',
            name='fquality',
            field=models.IntegerField(),
        ),
    ]
