# Generated by Django 4.0.2 on 2022-08-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_immigrations_alter_import1_fquality'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOEHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portCode', models.CharField(max_length=50)),
                ('priorentrystamp', models.CharField(max_length=50)),
                ('importdeptsno', models.IntegerField()),
                ('date', models.DateField()),
                ('customsbrokercode', models.CharField(max_length=50)),
                ('importcode', models.CharField(max_length=50)),
                ('importsname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('vesselsname', models.CharField(max_length=50)),
                ('rotationnodate', models.DateField()),
                ('lineno', models.IntegerField()),
                ('portofshipment', models.CharField(max_length=122)),
                ('countryoforigin', models.CharField(max_length=50)),
                ('coocode', models.IntegerField()),
                ('countryofconsignment', models.CharField(max_length=122)),
                ('coccode', models.IntegerField()),
                ('billofladingdate', models.DateField()),
                ('srno', models.IntegerField()),
                ('description', models.TextField()),
                ('marksandnumbers', models.IntegerField()),
                ('unitcode', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('ritcno', models.IntegerField()),
                ('custrffheading', models.TextField()),
                ('noofduty', models.IntegerField()),
                ('assessablevalue', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('cetheadind', models.TextField()),
                ('addvalue', models.IntegerField()),
                ('addrate', models.IntegerField()),
                ('totaladdduty', models.IntegerField()),
                ('gstcode', models.IntegerField()),
                ('igstrate', models.IntegerField()),
                ('exemptionandnotifiigst', models.FileField(upload_to='')),
                ('igstamount', models.IntegerField()),
                ('gstcomprate', models.IntegerField()),
                ('exemptionandnotifigst', models.FileField(upload_to='')),
                ('gstcompamount', models.IntegerField()),
                ('totalduty', models.IntegerField()),
            ],
        ),
    ]
