# Generated by Django 4.0.2 on 2022-08-25 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_boehome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=25)),
                ('age', models.IntegerField()),
                ('aadharcard', models.IntegerField(max_length=16)),
                ('address', models.TextField()),
                ('department', models.CharField(max_length=60)),
                ('stakeholderype', models.CharField(max_length=60)),
                ('employeeid', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
