# Generated by Django 4.0.2 on 2022-08-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='aadharcard',
            field=models.IntegerField(),
        ),
    ]
