# Generated by Django 4.0.2 on 2022-08-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_account_aadharcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='birthday',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='aadharcard',
            new_name='aadharcard_Number',
        ),
    ]
