# Generated by Django 4.0.2 on 2022-08-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_birthday_account_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='DOB',
            field=models.DateField(),
        ),
    ]
