# Generated by Django 4.0.2 on 2022-08-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_account_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boehome',
            old_name='cetheadind',
            new_name='cetheading',
        ),
    ]
