# Generated by Django 4.0.2 on 2022-08-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_boewarehousing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boewarehousing',
            name='amountofabadtement',
        ),
        migrations.AddField(
            model_name='boewarehousing',
            name='amountofabatement',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='boewarehousing',
            name='mrp',
            field=models.IntegerField(blank=b'I01\n', default=0),
        ),
    ]
