# Generated by Django 4.0.2 on 2022-08-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_boeexhome'),
    ]

    operations = [
        migrations.CreateModel(
            name='portoperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vesselid', models.CharField(max_length=20)),
                ('customsbrokerid', models.CharField(max_length=30)),
                ('harbourpilot', models.CharField(max_length=50)),
                ('tugboatid', models.CharField(max_length=20)),
                ('vesseloperator', models.CharField(max_length=50)),
                ('berthingdock', models.CharField(max_length=10)),
                ('numberofcontainers', models.IntegerField()),
                ('cranedriver', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=122)),
            ],
        ),
    ]
