# Generated by Django 4.0.2 on 2022-08-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_portoperations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portoperations',
            old_name='customsbrokerid',
            new_name='customsbroker',
        ),
    ]
