# Generated by Django 4.0.2 on 2022-08-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_customsbrokerid_portoperations_customsbroker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portoperations',
            old_name='customsbroker',
            new_name='cbid',
        ),
    ]
