# Generated by Django 4.0.2 on 2022-08-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_customsbroker_portoperations_cbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portaudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=60)),
                ('daudit', models.DateField()),
                ('taudit', models.CharField(max_length=30)),
                ('naudit', models.CharField(max_length=30)),
                ('gstin', models.IntegerField()),
                ('lname', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=6)),
            ],
        ),
    ]
