# Generated by Django 4.0.2 on 2022-08-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_portaudit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portaudit',
        ),
    ]
