# Generated by Django 4.0.2 on 2022-08-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_delete_portaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portaudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=60)),
                ('daudit', models.DateField()),
                ('taudit', models.CharField(max_length=30)),
                ('naudit', models.CharField(max_length=30)),
                ('gstin', models.IntegerField()),
                ('lname', models.CharField(max_length=30)),
                ('one', models.CharField(max_length=6)),
                ('review1', models.TextField(max_length=100)),
                ('sugg1', models.TextField(max_length=100)),
                ('two', models.CharField(max_length=100)),
                ('review2', models.TextField(max_length=100)),
                ('sugg2', models.TextField(max_length=100)),
                ('three', models.TextField(max_length=100)),
                ('review3', models.TextField(max_length=100)),
                ('sugg3', models.TextField(max_length=100)),
                ('x', models.CharField(max_length=20)),
                ('review4', models.TextField(max_length=100)),
                ('sugg4', models.TextField(max_length=100)),
            ],
        ),
    ]
