# Generated by Django 4.0.2 on 2022-08-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_portaudit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portaudit',
            old_name='x',
            new_name='four',
        ),
    ]
